# Use Node.js 14 as the base image
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy all project files into the working directory
COPY . .

# Build the React app for production
RUN npm run build

# Install 'serve' globally to serve the production build
RUN npm install -g serve

# Expose the port that 'serve' will use
EXPOSE 5000

# Command to serve the build using 'serve'
CMD ["serve", "-s", "build", "-l", "5000"]